import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import {SessionProvider} from "next-auth/react";
import SessionLayoutProvider from "@/app/Session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionLayoutProvider>
          {children}
      </SessionLayoutProvider>
      
      </body>
    </html>
  );
}
